### ISSUE TITLE
template is invalid, instructions do not work

### ISSUE THREAD

**Issue by pboling** [neo4j-contrib/neo4j-puppet#1]
Under the **Usage** section (on [Neo4j.org](http://www.neo4j.org/develop/ec2), and [here on the github project](https://github.com/neo4j-contrib/neo4j-puppet/blob/master/README.CLOUDFORMATION.md)):

```
1. Log onto the AWS CloudFormation console with your AWS account.
2. Click Create New Stack
3. Fill in the Stack Name field (whatever name you'd like)
4. Click the Provide a template URL radio button
5. Paste this link into the field next to the button
6. Click the Continue button
```

When clicking the Continue button there is an error:

```
ValidateTemplate failed: Template error: invalid Default for parameter AwsAvailabilityZone must be one of AllowedValues
```

It would appear that the template is invalid.

_Note:_ also reported [here](https://github.com/neo4j-contrib/neo4j-org/issues/72) as these same instructions appear on the Neo4j.org homepage.

**Comment by pboling** [comment]
The problem was 2 extra spaces in the default availability zone.  I downloaded the json, edited it to fix the problem, and uploaded it in the tool instead of using the link, and now it is working!

Bad:

```
"Default": "us-east-1d  "
```

Good:

```
"Default": "us-east-1d"
```

**Comment by simpsonjulian** [comment]
Sorry pboling, pneubauer fixed the error in source but didn't know he had to drop the template in an EC2 bucket.  I just did that.

**Comment by pboling** [comment]
Everything worked great!  I stood up a Neo4j server VERY quickly!  My only question is how the backup works.  It says the templates includes automatic backups of the Neo4j database.  Where should I look for them?  If needed how would i use a backup?  Is there documentation for this?

**Comment by jexp** [comment]
http://docs.neo4j.org/chunked/stable/operations-backup.html

**Comment by pboling** [comment]
Bookmarked, thanks! :)
