### ISSUE TITLE
neo4j creation

### ISSUE THREAD

**Issue by alexfrieden** [neo4j-contrib/neo4j-puppet#12]
I don't think this creates a neo4j installation on the aws instance.  Is this the intended behavior?

**Comment by simpsonjulian** [comment]
No.  The intended behaviour is to install Neo4j via the Debian package, which is orchestrated by Puppet.

What's probably happened is that something broke, which Puppet reported to a log file, and you haven't yet found that.

Suggest that you run:

`dpkg -l | grep neo4j`

And tell me if there's a Neo4j package installed.

I'm considering breaking apart the CloudFormation and Puppet components into different tools, because different audiences.  I'm open to comments on that.

Thanks!

**Comment by alexfrieden** [comment]
Pulled down onto new debian server: 
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  augeas-lenses bind9-host debconf-utils facter geoip-database libaugeas-ruby1.8 libaugeas0 libbind9-80 libclass-isa-perl libdns88 libffi5 libgeoip1 libisc84 libisccc80
  libisccfg82 liblwres80 libpci3 libreadline5 libruby1.8 libruby1.9.1 libswitch-perl libxml2 libyaml-0-2 pciutils perl perl-modules puppet-common ruby ruby-json ruby-shadow
  ruby1.8 ruby1.9.1 sgml-base xml-core
Suggested packages:
  augeas-doc augeas-tools geoip-bin bzip2 perl-doc libterm-readline-gnu-perl libterm-readline-perl-perl make libpod-plainer-perl puppet-el vim-puppet etckeeper ruby-selinux
  librrd-ruby1.8 ri ruby-dev ruby1.8-examples ri1.8 ruby-switch ruby1.9.1-examples ri1.9.1 graphviz ruby1.9.1-dev sgml-base-doc zip debhelper
Recommended packages:
  rdoc
The following NEW packages will be installed:
  augeas-lenses bind9-host debconf-utils facter geoip-database libaugeas-ruby1.8 libaugeas0 libbind9-80 libclass-isa-perl libdns88 libffi5 libgeoip1 libisc84 libisccc80
  libisccfg82 liblwres80 libpci3 libreadline5 libruby1.8 libruby1.9.1 libswitch-perl libxml2 libyaml-0-2 pciutils perl perl-modules puppet puppet-common ruby ruby-json
  ruby-shadow ruby1.8 ruby1.9.1 sgml-base unzip xml-core
0 upgraded, 36 newly installed, 0 to remove and 14 not upgraded.
Need to get 21.4 MB of archives.
After this operation, 68.8 MB of additional disk space will be used.
Get:1 http://security.debian.org/ wheezy/updates/main puppet-common all 2.7.23-1~deb7u2 [1,064 kB]
Get:2 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libpci3 amd64 1:3.1.9-6 [58.4 kB]
Get:3 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libxml2 amd64 2.8.0+dfsg1-7+nmu2 [905 kB]
Get:4 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main geoip-database all 20130213-1 [1,466 kB]
Get:5 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libffi5 amd64 3.0.10-3 [24.8 kB]
Get:6 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libreadline5 amd64 5.2+dfsg-2~deb7u1 [150 kB]
Get:7 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libyaml-0-2 amd64 0.1.4-2 [56.5 kB]
Get:8 http://security.debian.org/ wheezy/updates/main puppet all 2.7.23-1~deb7u2 [277 kB]
Get:9 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libruby1.9.1 amd64 1.9.3.194-8.1+deb7u2 [4,415 kB]
Get:10 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main ruby1.9.1 amd64 1.9.3.194-8.1+deb7u2 [209 kB]
Get:11 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main ruby all 1:1.9.3 [6,484 B]
Get:12 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libruby1.8 amd64 1.8.7.358-7.1+deb7u1 [2,091 kB]
Get:13 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main ruby1.8 amd64 1.8.7.358-7.1+deb7u1 [320 kB]
Get:14 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main ruby-json amd64 1.7.3-3 [78.5 kB]
Get:15 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libgeoip1 amd64 1.4.8+dfsg-3 [124 kB]
Get:16 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libisc84 amd64 1:9.8.4.dfsg.P1-6+nmu2+deb7u1 [182 kB]
Get:17 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libdns88 amd64 1:9.8.4.dfsg.P1-6+nmu2+deb7u1 [750 kB]
Get:18 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libisccc80 amd64 1:9.8.4.dfsg.P1-6+nmu2+deb7u1 [35.9 kB]
Get:19 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libisccfg82 amd64 1:9.8.4.dfsg.P1-6+nmu2+deb7u1 [62.8 kB]
Get:20 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libbind9-80 amd64 1:9.8.4.dfsg.P1-6+nmu2+deb7u1 [42.2 kB]
Get:21 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main liblwres80 amd64 1:9.8.4.dfsg.P1-6+nmu2+deb7u1 [55.2 kB]
Get:22 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main bind9-host amd64 1:9.8.4.dfsg.P1-6+nmu2+deb7u1 [73.4 kB]
Get:23 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main facter all 1.6.10-1 [68.4 kB]
Get:24 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main augeas-lenses all 0.10.0-1 [195 kB]
Get:25 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libaugeas0 amd64 0.10.0-1 [190 kB]
Get:26 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libaugeas-ruby1.8 amd64 0.4.1-1.1 [10.6 kB]
Get:27 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main ruby-shadow amd64 2.1.4-2 [13.3 kB]
Get:28 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libswitch-perl all 2.16-2 [21.0 kB]
Get:29 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main libclass-isa-perl all 0.36-3 [12.3 kB]
Get:30 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main perl-modules all 5.14.2-21+deb7u1 [3,440 kB]
Get:31 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main perl amd64 5.14.2-21+deb7u1 [4,407 kB]
Get:32 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main sgml-base all 1.26+nmu4 [14.6 kB]
Get:33 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main pciutils amd64 1:3.1.9-6 [280 kB]
Get:34 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main debconf-utils all 1.5.49 [55.8 kB]
Get:35 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main unzip amd64 6.0-8 [194 kB]
Get:36 http://gce_debian_mirror.storage.googleapis.com/ wheezy/main xml-core all 0.13+nmu2 [24.2 kB]
Fetched 21.4 MB in 3s (7,065 kB/s)
Extracting templates from packages: 100%
Selecting previously unselected package libpci3:amd64.
(Reading database ... 15826 files and directories currently installed.)
Unpacking libpci3:amd64 (from .../libpci3_1%3a3.1.9-6_amd64.deb) ...
Selecting previously unselected package libxml2:amd64.
Unpacking libxml2:amd64 (from .../libxml2_2.8.0+dfsg1-7+nmu2_amd64.deb) ...
Selecting previously unselected package geoip-database.
Unpacking geoip-database (from .../geoip-database_20130213-1_all.deb) ...
Selecting previously unselected package libffi5:amd64.
Unpacking libffi5:amd64 (from .../libffi5_3.0.10-3_amd64.deb) ...
Selecting previously unselected package libreadline5:amd64.
Unpacking libreadline5:amd64 (from .../libreadline5_5.2+dfsg-2~deb7u1_amd64.deb) ...
Selecting previously unselected package libyaml-0-2:amd64.
Unpacking libyaml-0-2:amd64 (from .../libyaml-0-2_0.1.4-2_amd64.deb) ...
Selecting previously unselected package libruby1.9.1.
Unpacking libruby1.9.1 (from .../libruby1.9.1_1.9.3.194-8.1+deb7u2_amd64.deb) ...
Selecting previously unselected package ruby1.9.1.
Unpacking ruby1.9.1 (from .../ruby1.9.1_1.9.3.194-8.1+deb7u2_amd64.deb) ...
Selecting previously unselected package ruby.
Unpacking ruby (from .../ruby_1%3a1.9.3_all.deb) ...
Selecting previously unselected package libruby1.8.
Unpacking libruby1.8 (from .../libruby1.8_1.8.7.358-7.1+deb7u1_amd64.deb) ...
Selecting previously unselected package ruby1.8.
Unpacking ruby1.8 (from .../ruby1.8_1.8.7.358-7.1+deb7u1_amd64.deb) ...
Selecting previously unselected package ruby-json.
Unpacking ruby-json (from .../ruby-json_1.7.3-3_amd64.deb) ...
Selecting previously unselected package libgeoip1.
Unpacking libgeoip1 (from .../libgeoip1_1.4.8+dfsg-3_amd64.deb) ...
Selecting previously unselected package libisc84.
Unpacking libisc84 (from .../libisc84_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u1_amd64.deb) ...
Selecting previously unselected package libdns88.
Unpacking libdns88 (from .../libdns88_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u1_amd64.deb) ...
Selecting previously unselected package libisccc80.
Unpacking libisccc80 (from .../libisccc80_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u1_amd64.deb) ...
Selecting previously unselected package libisccfg82.
Unpacking libisccfg82 (from .../libisccfg82_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u1_amd64.deb) ...
Selecting previously unselected package libbind9-80.
Unpacking libbind9-80 (from .../libbind9-80_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u1_amd64.deb) ...
Selecting previously unselected package liblwres80.
Unpacking liblwres80 (from .../liblwres80_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u1_amd64.deb) ...
Selecting previously unselected package bind9-host.
Unpacking bind9-host (from .../bind9-host_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u1_amd64.deb) ...
Selecting previously unselected package facter.
Unpacking facter (from .../facter_1.6.10-1_all.deb) ...
Selecting previously unselected package augeas-lenses.
Unpacking augeas-lenses (from .../augeas-lenses_0.10.0-1_all.deb) ...
Selecting previously unselected package libaugeas0.
Unpacking libaugeas0 (from .../libaugeas0_0.10.0-1_amd64.deb) ...
Selecting previously unselected package libaugeas-ruby1.8.
Unpacking libaugeas-ruby1.8 (from .../libaugeas-ruby1.8_0.4.1-1.1_amd64.deb) ...
Selecting previously unselected package ruby-shadow.
Unpacking ruby-shadow (from .../ruby-shadow_2.1.4-2_amd64.deb) ...
Selecting previously unselected package puppet-common.
Unpacking puppet-common (from .../puppet-common_2.7.23-1~deb7u2_all.deb) ...
Selecting previously unselected package puppet.
Unpacking puppet (from .../puppet_2.7.23-1~deb7u2_all.deb) ...
Selecting previously unselected package libswitch-perl.
Unpacking libswitch-perl (from .../libswitch-perl_2.16-2_all.deb) ...
Selecting previously unselected package libclass-isa-perl.
Unpacking libclass-isa-perl (from .../libclass-isa-perl_0.36-3_all.deb) ...
Selecting previously unselected package perl-modules.
Unpacking perl-modules (from .../perl-modules_5.14.2-21+deb7u1_all.deb) ...
Selecting previously unselected package perl.
Unpacking perl (from .../perl_5.14.2-21+deb7u1_amd64.deb) ...
Selecting previously unselected package sgml-base.
Unpacking sgml-base (from .../sgml-base_1.26+nmu4_all.deb) ...
Selecting previously unselected package pciutils.
Unpacking pciutils (from .../pciutils_1%3a3.1.9-6_amd64.deb) ...
Selecting previously unselected package debconf-utils.
Unpacking debconf-utils (from .../debconf-utils_1.5.49_all.deb) ...
Selecting previously unselected package unzip.
Unpacking unzip (from .../archives/unzip_6.0-8_amd64.deb) ...
Selecting previously unselected package xml-core.
Unpacking xml-core (from .../xml-core_0.13+nmu2_all.deb) ...
Processing triggers for man-db ...
Processing triggers for mime-support ...
Setting up libpci3:amd64 (1:3.1.9-6) ...
Setting up libxml2:amd64 (2.8.0+dfsg1-7+nmu2) ...
Setting up geoip-database (20130213-1) ...
Setting up libffi5:amd64 (3.0.10-3) ...
Setting up libreadline5:amd64 (5.2+dfsg-2~deb7u1) ...
Setting up libyaml-0-2:amd64 (0.1.4-2) ...
Setting up libruby1.9.1 (1.9.3.194-8.1+deb7u2) ...
Setting up ruby1.9.1 (1.9.3.194-8.1+deb7u2) ...
update-alternatives: using /usr/bin/gem1.9.1 to provide /usr/bin/gem (gem) in auto mode
update-alternatives: using /usr/bin/ruby1.9.1 to provide /usr/bin/ruby (ruby) in auto mode
Setting up ruby (1:1.9.3) ...
Setting up libruby1.8 (1.8.7.358-7.1+deb7u1) ...
Setting up ruby1.8 (1.8.7.358-7.1+deb7u1) ...
Setting up ruby-json (1.7.3-3) ...
Setting up libgeoip1 (1.4.8+dfsg-3) ...
Setting up libisc84 (1:9.8.4.dfsg.P1-6+nmu2+deb7u1) ...
Setting up libdns88 (1:9.8.4.dfsg.P1-6+nmu2+deb7u1) ...
Setting up libisccc80 (1:9.8.4.dfsg.P1-6+nmu2+deb7u1) ...
Setting up libisccfg82 (1:9.8.4.dfsg.P1-6+nmu2+deb7u1) ...
Setting up libbind9-80 (1:9.8.4.dfsg.P1-6+nmu2+deb7u1) ...
Setting up liblwres80 (1:9.8.4.dfsg.P1-6+nmu2+deb7u1) ...
Setting up bind9-host (1:9.8.4.dfsg.P1-6+nmu2+deb7u1) ...
Setting up facter (1.6.10-1) ...
Setting up augeas-lenses (0.10.0-1) ...
Setting up libaugeas0 (0.10.0-1) ...
Setting up libaugeas-ruby1.8 (0.4.1-1.1) ...
Setting up ruby-shadow (2.1.4-2) ...
Setting up puppet-common (2.7.23-1~deb7u2) ...
Setting up puppet (2.7.23-1~deb7u2) ...
[....] Starting puppet agent
puppet not configured to start, please edit /etc/default/puppet to enable
. ok
Setting up libclass-isa-perl (0.36-3) ...
Setting up pciutils (1:3.1.9-6) ...
Setting up debconf-utils (1.5.49) ...
Setting up unzip (6.0-8) ...
Setting up perl-modules (5.14.2-21+deb7u1) ...
Setting up libswitch-perl (2.16-2) ...
Setting up perl (5.14.2-21+deb7u1) ...
update-alternatives: using /usr/bin/prename to provide /usr/bin/rename (rename) in auto mode
Setting up sgml-base (1.26+nmu4) ...
Setting up xml-core (0.13+nmu2) ...
Processing triggers for sgml-base ...

---

****\* By using this you agree to the terms of the Oracle License Agreement *****

---

notice: Scope(Class[Neo4j::Java]): Proceeding with the Oracle JVM as you agree to the license agreement
notice: /Stage[main]/Neo4j::Ubuntu/Exec[neotech signing key]/returns: executed successfully
notice: /Stage[main]/Neo4j::Ubuntu/File[neo4j apt config]/ensure: defined content as '{md5}891666292772f70a56740cb1556cdf26'
notice: /Stage[main]/Neo4j::Ubuntu/File[neo4j contrib dir]/ensure: created
notice: /Stage[main]/Neo4j::Linux/Exec[neo4j_security_limits]/returns: executed successfully
notice: /Stage[main]/Neo4j::Java/Exec[apt-get update for OAB dependencies]/returns: executed successfully
notice: /Stage[main]/Neo4j::Java/Exec[download OAB]/returns: executed successfully
notice: /Stage[main]/Neo4j::Java/File[/tmp/oab-java.sh]/mode: mode changed '0644' to '0755'
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: oab-java.sh v0.3.1-dev - Create a local 'apt' repository for Sun Java 6 and/or Oracle Java 7 packages.
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: Copyright (c) Martin Wimpress, http://flexion.org. MIT License
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: By running this script to download Java you acknowledge that you have
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: read and accepted the terms of the Oracle end user license agreement.
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: \* http://www.oracle.com/technetwork/java/javase/terms/license/
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: If you want to see what this is script is doing while it is running then execute
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: the following from another shell:
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:     tail -f /var/tmp/oab-java.sh.log
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:  [x] Adding i386 architecture success
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:  [x] Update package list success
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:  [x] Installing Java build requirements success
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:  [x] Making build directories success
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:  [x] Mirroring https://github.com/rraptorr/sun-java6 failed
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:  [i] Showing the last 5 lines from the logfile (/var/tmp/oab-java.sh.log)...
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:  [x] Making build directories 4001's retcode: 0
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: success
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns:  [x] Mirroring https://github.com/rraptorr/sun-java6   /tmp/oab-java.sh: line 443: git: command not found
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns4009's retcode: 127
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: failed
err: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: change from notrun to 0 failed: /tmp/oab-java.sh returned 1 instead of one of [0] at /var/tmp/neo4j/manifests/java.pp:51
notice: /Stage[main]/Neo4j::Ubuntu/Exec[apt-get update]: Dependency Exec[install OAB repo] has failures: true
warning: /Stage[main]/Neo4j::Ubuntu/Exec[apt-get update]: Skipping because of failed dependencies
notice: /Stage[main]/Neo4j::Java/Package[sun-java6-jdk]: Dependency Exec[install OAB repo] has failures: true
warning: /Stage[main]/Neo4j::Java/Package[sun-java6-jdk]: Skipping because of failed dependencies
notice: /Stage[main]/Neo4j::Java/Exec[default JVM]: Dependency Exec[install OAB repo] has failures: true
warning: /Stage[main]/Neo4j::Java/Exec[default JVM]: Skipping because of failed dependencies
notice: /Stage[main]/Neo4j::Ubuntu/Package[neo4j]: Dependency Exec[install OAB repo] has failures: true
warning: /Stage[main]/Neo4j::Ubuntu/Package[neo4j]: Skipping because of failed dependencies
notice: /Stage[main]/Neo4j::Ubuntu/Exec[bump the minimum heap size]: Dependency Exec[install OAB repo] has failures: true
warning: /Stage[main]/Neo4j::Ubuntu/Exec[bump the minimum heap size]: Skipping because of failed dependencies
notice: /Stage[main]/Neo4j::Ubuntu/Exec[bump the maximum heap size]: Dependency Exec[install OAB repo] has failures: true
warning: /Stage[main]/Neo4j::Ubuntu/Exec[bump the maximum heap size]: Skipping because of failed dependencies
notice: /Stage[main]/Neo4j::Ubuntu/File[neo4j config file]: Dependency Exec[install OAB repo] has failures: true
warning: /Stage[main]/Neo4j::Ubuntu/File[neo4j config file]: Skipping because of failed dependencies
notice: /Stage[main]/Neo4j::Linux/Exec[neo4j_pam_limits]/returns: executed successfully
notice: /Stage[main]/Neo4j::Ubuntu/File[neo4j auth extension]/ensure: defined content as '{md5}b2266170c74dbe0447da9667097980eb'
err: /Stage[main]/Neo4j::Ubuntu/File[neo4j auth extension link]/ensure: change from absent to link failed: Could not set 'link on ensure: No such file or directory - /usr/share/neo4j/plugins at /var/tmp/neo4j/manifests/ubuntu.pp:88
notice: /Stage[main]/Neo4j::Ubuntu/Exec[restart neo4j]: Dependency Exec[install OAB repo] has failures: true
notice: /Stage[main]/Neo4j::Ubuntu/Exec[restart neo4j]: Dependency File[neo4j auth extension link] has failures: true
warning: /Stage[main]/Neo4j::Ubuntu/Exec[restart neo4j]: Skipping because of failed dependencies
notice: /Stage[main]/Neo4j::Ubuntu/Service[neo4j-service]: Dependency Exec[install OAB repo] has failures: true
notice: /Stage[main]/Neo4j::Ubuntu/Service[neo4j-service]: Dependency File[neo4j auth extension link] has failures: true
warning: /Stage[main]/Neo4j::Ubuntu/Service[neo4j-service]: Skipping because of failed dependencies
notice: Finished catalog run in 24.85 seconds

Not sure how to fix the failure in ubuntu.pp . I am running on debian which might be the problem?

**Comment by simpsonjulian** [comment]
I'm working on a new version of this at github.com/simpsonjulian/ec2neo - would you mind checking that out as an alternative?

**Comment by alexfrieden** [comment]
Ya sure thing!

**Comment by alexfrieden** [comment]
Running into: The volume 'vol-9a41add8' is not in the same availability zone as instance 'i-5d9bf47d' but the volumes in the json template are just a function of the availability zones.

**Comment by simpsonjulian** [comment]
I'm guessing that the volume hasn't got an AZ specified?  Which template are you using?

**Comment by alexfrieden** [comment]
https://cf-templates.neo4j.org.s3.amazonaws.com/amazon_linux.json

On Tue, Jan 14, 2014 at 11:52 AM, Julian Simpson
notifications@github.comwrote:

> I'm guessing that the volume hasn't got an AZ specified? Which template
> are you using?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/neo4j-contrib/neo4j-puppet/issues/12#issuecomment-32282899
> .

## 

Alexander Frieden

**Comment by simpsonjulian** [comment]
I pushed a change to address that, but RPM's won't work correctly until 2.0.1 is out (soon).  Ubuntu should work OK.

**Comment by alexfrieden** [comment]
worked perfectly for ubuntu!

**Comment by simpsonjulian** [comment]
Glad to hear it!
