### ISSUE TITLE
CREATE_FAILED	The image id 'ami-e7beec8e' does not exist

### ISSUE THREAD

**Issue by ahoffer** [neo4j-contrib/neo4j-puppet#14]
Followed instructions here:
http://www.neo4j.org/develop/ec2

Process failed with this event:
**CREATE_FAILED The image id 'ami-e7beec8e' does not exist**

**Comment by simpsonjulian** [comment]
@ahoffer if you're interested in using puppet, let's discuss that.  Otherwise you might find https://github.com/neo4j-contrib/ec2neo more useful.
