### ISSUE TITLE
error while setting up EC2 instance and Neo4j using Puppet via CloudFormation

### ISSUE THREAD

**Issue by arikan** [neo4j-contrib/neo4j-puppet#2]
Hi there,

Trying to setup an EC2 instance and Neo4j using Puppet via CloudFormation stack, as described here http://www.neo4j.org/develop/ec2

But it throws the error below (seen in the Stack Events) and rolls back, so the status says ROLLBACK_COMPLETE.

AWS::EC2::Instance Server CREATE_FAILED

Any idea how to resolve it?

**Comment by simpsonjulian** [comment]
That was Amazon telling you that they ran out of server resources.  Just try again ...

**Comment by arikan** [comment]
Thanks.

**Comment by scottforte** [comment]
I have the same issue... I've deleted the stack after I get the ROLLBACK_COMPLETE status and tried again 4x so far... any thoughts?

**Comment by simpsonjulian** [comment]
You can try a different availability zone.  If anybody wants to add other regions to the cloud formation template, I'm accepting patches.
