### ISSUE TITLE
Improving default configuration & removing Deprecation warnings

### ISSUE THREAD

**Issue by pboling** [neo4j-contrib/neo4j-puppet#4]
These kinds of messages in the log seem like low hanging fruit.
1. `INFO ... Could NOT find resource [logback.groovy]`
2. `INFO ... Could NOT find resource [logback-test.xml]`
3. `ERROR ... Could not find resource corresponding to [custom-logback.xml]`
4. And this one
   
   ```
   WARNING! Deprecated configuration options used. See manual for details
   cannot configure writers and searchers individually since they go together
   ```

Also, is the `ERROR` of not finding the logback file going to prevent me from doing a recovery?

**Comment by simpsonjulian** [comment]
I agree that they are confusing to the casual reader.  They cannot be fixed in this project though - you need to raise that in the main Neo4j project:

https://github.com/neo4j/neo4j

**Comment by pboling** [comment]
[Done.](https://github.com/neo4j/neo4j/issues/625)

**Comment by simpsonjulian** [comment]
Thanks Peter!
