### ISSUE TITLE
Error mounting /backup when using puppet

### ISSUE THREAD

**Issue by jobrieniii** [neo4j-contrib/neo4j-puppet#6]
Fresh install of Ubuntu on EC2 (version Ubuntu Server 12.04.2 LTS so slightly different than instructions).

Near end of install get error:

err: /Stage[main]/Neo4j::Ebs/Mount[/backup]: Could not evaluate: Execution of '/bin/mount -o nosuid /backup' returned 32: mount: special device /dev/xvdj does not exist

Neo4J seems to be running fine after the install, but a reboot of the server seems to put the server into a situation where it won't finalize the boot sequence / or ends up waiting.

1) I can't ssh to the server after the reboot (if I do it before the neo4j install it seems fine).

2) and I see things such as this in the system log (from EC2 Mgmt Console):

[1978250.838394] EXT3-fs (xvdb): mounted filesystem with ordered data mode
The disk drive for /backup is not ready yet or not present.

Continue to wait, or Press S to skip mounting or M for manual recovery

which is where is seemed to hang.  

Kind of stuck - and don't feel like writing code to start learning more about Neo4j until I know I have the server stable.

John

**Comment by jobrieniii** [comment]
And one more comment I was using the Install with Puppet: Advanced Usage instructions located at http://www.neo4j.org/download/linux

**Comment by jobrieniii** [comment]
OK - I just spent a few moments doing what I should have done first - and pay attention to where the mounts were going.  

I went ahead and ensured it the EBS attached during setup was at /dev/xvdj and everyone went much smoother.  

Closing...

**Comment by darKoram** [comment]
I'm having the same issue.  Could you be a little more explicit on how you solved it?  How to you ensure the EBS is at /dev/xvdj?

**Comment by simpsonjulian** [comment]
The Puppet scripts assume that the EBS filesystem is available as a particular device.  When you mount a filesystem you can specify the device name, and hence the scripts will work.  If someone wants to add a parameter to the scripts or find a clever custom fact to expose the EBS device names to Puppet, I'd gladly accept the PR.

HTH

Julian.
