### ISSUE TITLE
neo4j puppet error

### ISSUE THREAD

**Issue by pranaydoshi** [neo4j-contrib/neo4j-puppet#9]
Hi

While installing neo4j using puppet on my brand new EC2 instance with Ubuntu 64-bit 12.04 LTS, I get the an error related to jce-policy.zip not being downloaded:

notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: [x] Downloading jce_policy-6.zip : failed
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: [i] Showing the last 5 lines from the logfile (/var/tmp/oab-java.sh.log)...
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: [x] Downloading jce_policy-6.zip : --2013-10-16 08:12:34-- http://jce_policy-6.zip/
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: Resolving jce_policy-6.zip (jce_policy-6.zip)... failed: Name or service not known.
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: wget: unable to resolve host address `jce_policy-6.zip'
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns14187's retcode: 4
notice: /Stage[main]/Neo4j::Java/Exec[install OAB repo]/returns: failed

How do we resolve this ?

**Comment by drzax** [comment]
I get what looks to be the same issue _when I do accept the Oracle license agreement_ (but another, see #8) when not accepting the agreement.

The full console output from running `./go true bob bob123` [is here](http://pastebin.com/qaiNT1tQ).

The problem seems to trace back the external dependency on [oab-java6.sh at around line 525](https://github.com/flexiondotorg/oab-java6/blob/master/oab-java.sh#L525). It looks as though this involves scraping a website to get a URL. Maybe the website structure has changed? 

I noticed that the `java.pp` manifest downloads `https://github.com/flexiondotorg/oab-java6/raw/0.2.7/oab-java.sh` and there is a newer version of that file (`0.3.0`) available. Changing the `0.3.0` seems to fix the policy download failure, however the neo4j service still fails to start with the following error:

```
err: /Stage[main]/Neo4j::Ubuntu/Exec[restart neo4j]/returns: change from notrun to 0 failed: /usr/sbin/service neo4j-service restart returned 1 instead of one of [0] at /var/tmp/neo4j/manifests/ubuntu.pp:59
```

Content of `/var/log/neo4j/console.log`:

```
root@neo4j:/var/tmp# cat /var/log/neo4j/console.log
10/17/13 11:00:28 PM org.neo4j.server.CommunityBootstrapper WARNING: WARNING! You are using an unsupported version of the Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 7.
10/17/13 11:00:28 PM org.neo4j.server.AbstractNeoServer INFO: Setting startup timeout to: 120000ms based on -1
23:00:28.829 [main] WARN  o.neo4j.kernel.EmbeddedGraphDatabase - WARNING! You are using an unsupported version of the Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 7.
10/17/13 11:00:30 PM org.neo4j.server.database.Database INFO: Successfully started database
10/17/13 11:00:30 PM org.neo4j.server.AbstractNeoServer INFO: Starting Neo Server on port [7474] with [10] threads available
10/17/13 11:00:30 PM org.neo4j.server.AbstractNeoServer INFO: Enabling HTTPS on port [7473]
10/17/13 11:00:30 PM org.neo4j.server.AbstractNeoServer INFO: No SSL certificate found, generating a self-signed certificate..
10/17/13 11:00:32 PM org.neo4j.server.modules.DiscoveryModule INFO: Mounted discovery module at [/]
10/17/13 11:00:32 PM org.neo4j.server.plugins.PluginManager INFO: Loaded server plugin "CypherPlugin"
10/17/13 11:00:32 PM org.neo4j.server.plugins.PluginManager INFO: Loaded server plugin "GremlinPlugin"
10/17/13 11:00:32 PM org.neo4j.server.modules.RESTApiModule INFO: Mounted REST API at [/db/data/]
10/17/13 11:00:32 PM org.neo4j.server.modules.ManagementApiModule INFO: Mounted management API at [/db/manage/]
10/17/13 11:00:32 PM org.neo4j.server.modules.WebAdminModule INFO: Mounted webadmin at [/webadmin]
23:00:32.542 [main] INFO  org.mortbay.log - Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
10/17/13 11:00:32 PM org.neo4j.server.web.Jetty6WebServer INFO: Mounting static content at [/webadmin] from [webadmin-html]
23:00:32.608 [main] INFO  org.mortbay.log - jetty-6.1.25
23:00:32.723 [main] INFO  org.mortbay.log - NO JSP Support for /webadmin, did not find org.apache.jasper.servlet.JspServlet
23:00:34.693 [main] INFO  org.mortbay.log - Started SelectChannelConnector@localhost:7474
23:00:35.006 [main] INFO  org.mortbay.log - Started SslSocketConnector@localhost:7473
10/17/13 11:00:35 PM org.neo4j.server.AbstractNeoServer INFO: Server started on [http://localhost:7474/]
10/17/13 11:00:36 PM org.neo4j.server.CommunityBootstrapper INFO: Neo4j Server shutdown initiated by kill signal
23:00:36.381 [Thread-8] INFO  org.mortbay.log - Stopped SslSocketConnector@localhost:7473
23:00:36.382 [Thread-8] INFO  org.mortbay.log - Stopped SelectChannelConnector@localhost:7474
Error occurred during initialization of VM
Could not reserve enough space for object heap
```

**Comment by simpsonjulian** [comment]
Hey @pranaydoshi 

I fixed the issue, but found another, which I need to fix.

@drzax you were correct about the issue with OAB.  I've pushed that fix, cheers.

**Comment by simpsonjulian** [comment]
@pranaydoshi you're all set.  This not working exposed an issue with our Debian packaging, which has been fixed now.  Thanks for raising this!
